const Collections = {
  CANDIDATE: 'candidate',
  CANDIDATE_STATUS: 'candidateStatus',
  LOGS: 'logs',
  LOGIN_LOGS: 'loginLogs',
  ORGANIZATION: 'organizations',
  ROLES_AND_ACCESS: 'rolesAndAccess',
  TEAM_INFO: 'teamInfo',
  TOKENS: 'tokens',
  TEMPLATES: 'templates',
  USER: 'users',
  USER_PROFILE_INFO: 'userProfileInfo',
  WORK_INFO: 'workInfo',
  USER_PROFILE_IMAGE: 'userProfileImage',
  TASKS: 'tasks',
  CANDIDATE_TASKS: 'candidateTasks',
  SIGNATURE: 'signature',
  EMPLOYMENT_TYPE: 'employmentTypes',
  LOCATIONS: 'locations',
  ROLES: 'roles',
  BENEFIT_GROUP: 'benefitGroups',
  BENEFITPLANS: 'benefitPlans',
  EXECUTED_DOCUMENTS: 'executedDocuments',
  TIME_CARD: 'timeCard',
  ORGANIZATION_MEMBERS: 'organizationMembers',
  ELIGIBILITY_RULE: 'eligibilityRules',
  LOCATION_OF_OPERATIONS: 'locationOfOperations',
  SPECIALTY: 'specialty',
  EMPLOYEE_FOLDER: 'employeeFolders',
  EMPLOYEE_FILE: 'employeeFiles',
  ORGANIZATION_FOLDER: 'organizationFolders',
  ORGANIZATION_FILE: 'organizationFiles',
  TIME_OFF_TYPE: 'timeOffTypes',
  TIME_OFF_POLICY: 'timeOffPolicies',
  REQUEST_TIME_OFF: 'requestTimeOff',
  USER_LEAVES: 'userLeaves',
  ESIGNATURE: 'esignatures',
  REQUEST_TIME_OFF: 'requestTimeCard',
  TODOS: 'todos',
  POLICIES_ASSIGNED: 'policiesAssigned',
};

module.exports = Collections;
